services:
  raffosberrybot:
    container_name: raffosberrybot
    environment:
      - PYTHONUNBUFFERED=1

      - API_TOKEN=${API_TOKEN:-placeholder}

      - OWNER_ID=${OWNER_ID:-123456789}

      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-placeholder}
    ports:
      - "8222:${FLASK_PORT}"
    restart: unless-stopped
    build: .
    pull_policy: build
    volumes:
      - ${MEDIA_DIRECTORY}:/app/Downloads